"""Public API of the radar-scoring package."""

from .scoring import (
    SMOOTHING_STARS,
    SCORING_VERSION,
    STATUS_BANDS,
    BreakoutResult,
    CorpusStats,
    Metrics,
    Snapshot,
    CATEGORIES,
    acceleration_hint,
    acceleration_pct,
    age_bonus,
    classify_category,
    classify_status,
    compute_breakout,
    compute_corpus_stats,
    compute_metrics,
    corpus_transform,
    explain_score,
    hype_risk_details,
    robust_norm,
)

__all__ = [
    "SMOOTHING_STARS",
    "SCORING_VERSION",
    "STATUS_BANDS",
    "BreakoutResult",
    "CorpusStats",
    "Metrics",
    "Snapshot",
    "CATEGORIES",
    "acceleration_hint",
    "age_bonus",
    "classify_category",
    "classify_status",
    "compute_breakout",
    "compute_corpus_stats",
    "compute_metrics",
    "explain_score",
    "robust_norm",
    "acceleration_pct",
    "corpus_transform",
    "hype_risk_details",
]
